import { useEffect, useRef, useState } from "react";
import { Camera, CameraOff, Check, LoaderCircle, Mic, MicOff, Send, Volume2 } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { toast } from "sonner";
import { completeInterview, evaluateAnswer, generateInterview, saveAnswer } from "../../lib/api";
import type { InterviewData, Question } from "../../lib/types";

type SpeechRecognitionCtor = new () => any;
declare global { interface Window { SpeechRecognition?: SpeechRecognitionCtor; webkitSpeechRecognition?: SpeechRecognitionCtor; } }

export default function InterviewPage(){
 const {sessionId}=useParams(); const navigate=useNavigate(); const [questions,setQuestions]=useState<Question[]>([]); const [index,setIndex]=useState(0); const [answer,setAnswer]=useState(""); const [listening,setListening]=useState(false); const [speaking,setSpeaking]=useState(false); const [saving,setSaving]=useState(false); const [cameraOn,setCameraOn]=useState(false); const [cameraError,setCameraError]=useState(""); const [started,setStarted]=useState(false); const [elapsed,setElapsed]=useState(0);
 const videoRef=useRef<HTMLVideoElement>(null); const streamRef=useRef<MediaStream|null>(null); const startedAt=useRef(Date.now()); const recognitionRef=useRef<SpeechRecognition|null>(null);
 const question=questions[index];

 useEffect(()=>{ if(!sessionId)return; const raw=localStorage.getItem("mockmind_questions"); if(raw){try{const data=JSON.parse(raw) as InterviewData;if(String(data.session_id)===sessionId)setQuestions(data.questions)}catch{}} },[sessionId]);
 useEffect(()=>{const id=setInterval(()=>setElapsed(Math.floor((Date.now()-startedAt.current)/1000)),1000);return()=>clearInterval(id)},[]);
 useEffect(()=>()=>{streamRef.current?.getTracks().forEach(t=>t.stop());recognitionRef.current?.stop();speechSynthesis.cancel()},[]);
 useEffect(()=>{if(question&&!started) speak(question.question)},[question,started]);

 async function prepareCamera(){try{const stream=await navigator.mediaDevices.getUserMedia({video:true,audio:true});streamRef.current=stream;if(videoRef.current)videoRef.current.srcObject=stream;setCameraOn(true)}catch{setCameraError("Camera permission was not granted. You can still continue with voice/text.")}}
 async function speak(text:string){setSpeaking(true);speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=.96;u.pitch=1;u.onend=()=>{setSpeaking(false);if(started)startListening()};speechSynthesis.speak(u)}
 function startListening(){const C=window.SpeechRecognition??window.webkitSpeechRecognition;if(!C){setListening(false);return} const r=new C();r.continuous=false;r.interimResults=true;r.lang="en-US";r.onstart=()=>setListening(true);r.onend=()=>setListening(false);r.onresult=e=>{let text="";for(let i=e.resultIndex;i<e.results.length;i++)text+=e.results[i][0].transcript;if(e.results[e.results.length-1].isFinal)setAnswer(text)};recognitionRef.current=r;r.start()}
 function begin(){setStarted(true);startedAt.current=Date.now();prepareCamera();setTimeout(()=>question&&speak(question.question),350)}
 async function submit(){if(!question||!sessionId||!answer.trim())return;setSaving(true);recognitionRef.current?.stop();speechSynthesis.cancel();try{const saved=await saveAnswer({session_id:Number(sessionId),question_number:question.question_number,answer_text:answer.trim(),answer_duration:Math.max(1,elapsed)});await evaluateAnswer(saved.id);if(index===questions.length-1){const result=await completeInterview(Number(sessionId));navigate(`/results/${sessionId}`,{state:result})}else{setAnswer("");setIndex(i=>i+1);setTimeout(()=>speak(questions[index+1].question),350)}}catch(err:any){toast.error(err?.response?.data?.detail??"Could not save this answer.")}finally{setSaving(false)}}
 if(!question)return <main className="loading-screen"><LoaderCircle className="spin" size={28}/><p>Loading your interview room…</p></main>;
 return <main className="interview-shell"><header className="interview-top"><div className="brand"><span className="brand-mark">M</span> MOCK MIND</div><div className="progress-text">QUESTION {index+1} / {questions.length}</div><div className="timer">{String(Math.floor(elapsed/60)).padStart(2,"0")}:{String(elapsed%60).padStart(2,"0")}</div></header>
 <div className="interview-grid"><aside className="interviewer-card"><div className="ai-avatar"><div className="ai-core"/></div><div className="live-pill"><span/> AI INTERVIEWER</div><h2>Mock Mind</h2><p>{speaking?"Asking your question…":listening?"Listening to you…":"Take your time."}</p><div className="voice-bars">{[1,2,3,4,5,6,7].map(n=><i className={(speaking||listening)? "active":""} key={n}/>)}</div></aside>
 <section className="conversation"><div className="question-meta"><span>{question.category}</span><span>{question.difficulty}</span></div><h1>{question.question}</h1><div className="answer-area"><div className="answer-head"><span>Your answer</span><span>{answer.length} chars</span></div><textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Speak naturally. Your transcript will appear here…" onFocus={()=>{if(!listening&&!speaking)startListening()}}/><div className="answer-tools"><button className={listening?"tool-btn active":"tool-btn"} onClick={()=>listening?recognitionRef.current?.stop():startListening()}>{listening?<MicOff size={17}/>:<Mic size={17}/>} {listening?"Stop listening":"Use microphone"}</button><button className="tool-btn" onClick={()=>speak(question.question)} disabled={speaking}><Volume2 size={17}/> Repeat</button><button className="send-btn" onClick={submit} disabled={saving||!answer.trim()}>{saving?<LoaderCircle className="spin" size={17}/>:<Send size={17}/>} Submit answer</button></div><p className="skip-note">If you genuinely don’t know, say “Sorry, I don’t know the answer.” It will be recorded and evaluated as part of the interview.</p></div></section>
 <aside className="camera-card"><div className="camera-head"><span>CAMERA</span><span className={cameraOn?"camera-status on":"camera-status"}>{cameraOn?"LIVE":"OFF"}</span></div><div className="video-wrap">{cameraOn?<video ref={videoRef} autoPlay muted playsInline/>:<div className="camera-off"><CameraOff size={28}/><span>{cameraError||"Camera is off"}</span><button className="ghost-btn" onClick={prepareCamera}>Enable camera</button></div>}</div><div className="signal-note"><Camera size={15}/> Video is being prepared for future confidence analysis.</div></aside></div>
 {!started&&<div className="start-overlay"><div className="start-modal"><div className="eyebrow">INTERVIEW READY</div><h2>Your interviewer is ready.</h2><p>We’ll ask one question at a time. The AI will speak, you answer naturally, and the transcript is evaluated automatically.</p><div className="permission-list"><span><Mic/> Microphone</span><span><Camera/> Camera</span></div><button className="primary-btn large" onClick={begin}><Check size={18}/> Enter interview room</button></div></div>}</main>
}
