"""create interview sessions table

Revision ID: c3fe5c8b3727
Revises: 587c48f87d01
Create Date: 2026-07-04 18:35:53.938214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3fe5c8b3727'
down_revision: Union[str, Sequence[str], None] = '587c48f87d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resume_analysis_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resume_analysis_id'], ['resume_analysis.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_sessions_id'), 'interview_sessions', ['id'], unique=False)
    op.add_column('interview_questions', sa.Column('interview_session_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('interview_questions_resume_analysis_id_fkey'), 'interview_questions', type_='foreignkey')
    op.create_foreign_key(None, 'interview_questions', 'interview_sessions', ['interview_session_id'], ['id'])
    op.drop_column('interview_questions', 'resume_analysis_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_questions', sa.Column('resume_analysis_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'interview_questions', type_='foreignkey')
    op.create_foreign_key(op.f('interview_questions_resume_analysis_id_fkey'), 'interview_questions', 'resume_analysis', ['resume_analysis_id'], ['id'])
    op.drop_column('interview_questions', 'interview_session_id')
    op.drop_index(op.f('ix_interview_sessions_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    # ### end Alembic commands ###
