"""add question number

Revision ID: e39bfb9e2aa2
Revises: b243a5caa467
Create Date: 2026-07-05 18:25:09.507431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e39bfb9e2aa2'
down_revision: Union[str, Sequence[str], None] = 'b243a5caa467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_questions', sa.Column('question_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_questions', 'question_number')
    # ### end Alembic commands ###
